/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 1, 2, 3, 7, 8, 9, 10, 14, 15, 16, 17 };

// (before - mean) / scale
const float ei_classifier_anom_scale[12] = { 2.6181340424017643, 2.575014164762794, 2.932444707954435, 2.6264303077660283, 11.619437938375297, 13.125701912897894, 11.042753389031311, 11.518000464046743, 73.086481089401, 70.4648208343558, 117.7370574434516, 77.45093971055044 };
const float ei_classifier_anom_mean[12] = { 30.32143434885386, 29.90993673376135, 30.723316388516814, 30.332869914286846, 53.17427104022052, 51.58813156746529, 54.74726440635887, 53.27671156393515, 108.69396350686652, 93.0215207656798, 133.65171479691273, 112.41995716471473 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[3] = {
	{ ( float[12] ) { -0.3932178020477295, -0.4849320352077484, -0.27442947030067444, -0.39172467589378357, -1.77578866481781, -1.6689997911453247, -1.6361277103424072, -1.773970603942871, -0.84465092420578, -0.6874144077301025, -0.6927130818367004, -0.8327778577804565 }, 4.516152319862575 },
	{ ( float[12] ) { -0.5593277215957642, -0.46602100133895874, -0.5540697574615479, -0.560640275478363, 0.07684729993343353, 0.08338548988103867, 0.023676332086324692, 0.07284653186798096, -0.20562483370304108, -0.12796741724014282, -0.23032885789871216, -0.22466181218624115 }, 3.567799584993766 },
	{ ( float[12] ) { 1.3524181842803955, 1.217612624168396, 1.275025725364685, 1.3539291620254517, 1.0599086284637451, 1.0205399990081787, 1.0190609693527222, 1.0609691143035889, 0.9969375729560852, 0.6957616806030273, 1.0029709339141846, 1.0448492765426636 }, 6.10205457097577 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
